module;

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonParseError>
#include <QSaveFile>
#include <QSet>
#include <algorithm>
#include <functional>

module pds.native.token.generator;

import std;

namespace pds::native::token {
namespace {

constexpr auto generatedBanner = "// Generated by PdsTokenGenerator. Do not edit.\n";
const QSet<QString> categories{
    "blur", "breakpoint", "color", "gradient", "motion", "radius",
    "shadow", "spacing", "typography"};
const QSet<QString> types{
    "color", "number", "duration", "fontFamily", "fontWeight", "easing", "string"};

[[nodiscard]] auto typeMatches(const QString& category, const QString& type) -> bool
{
    if (category == "color") {
        return type == "color";
    }
    if (category == "motion") {
        return type == "duration" || type == "easing";
    }
    if (category == "typography") {
        return type == "number" || type == "fontFamily" || type == "fontWeight"
            || type == "string";
    }
    if (category == "spacing") {
        return type == "number" || type == "string";
    }
    if (category == "gradient" || category == "shadow") {
        return type == "string";
    }
    return type == "number";
}

[[nodiscard]] auto literalMatches(const QString& type, const QJsonValue& value) -> bool
{
    if (value.isString()) {
        const auto text = value.toString();
        if (text.size() >= 3 && text.startsWith('{') && text.endsWith('}')) {
            return true;
        }
    }
    if (type == "color" || type == "fontFamily" || type == "easing"
        || type == "string") {
        return value.isString();
    }
    return value.isDouble();
}

[[nodiscard]] auto aliasId(const QJsonValue& value) -> QString
{
    if (!value.isString()) {
        return {};
    }
    const auto text = value.toString();
    if (text.size() >= 3 && text.startsWith('{') && text.endsWith('}')) {
        return text.mid(1, text.size() - 2);
    }
    return {};
}

[[nodiscard]] auto qmlLiteral(const QJsonValue& value) -> QString
{
    if (value.isString()) {
        QString escaped = value.toString();
        escaped.replace('\\', "\\\\").replace('"', "\\\"");
        return '"' + escaped + '"';
    }
    if (value.isBool()) {
        return value.toBool() ? "true" : "false";
    }
    if (value.isDouble()) {
        return QString::number(value.toDouble(), 'g', 15);
    }
    return "undefined";
}

[[nodiscard]] auto cppName(const QString& id) -> QString
{
    auto result = id;
    if (!result.isEmpty()) {
        result[0] = result[0].toUpper();
    }
    return result;
}

[[nodiscard]] auto parse(
    const QByteArray& bytes,
    QVector<Token>* output,
    QHash<QString, QJsonObject>* byId
) -> Result
{
    Result result{true, {}};
    QJsonParseError error;
    const auto document = QJsonDocument::fromJson(bytes, &error);
    if (error.error != QJsonParseError::NoError) {
        return {false, {QString("JSON parse error at offset %1: %2")
                            .arg(error.offset)
                            .arg(error.errorString())}};
    }
    if (!document.isObject() || !document.object().value("tokens").isArray()) {
        return {false, {"Root must be an object containing a 'tokens' array."}};
    }

    const auto array = document.object().value("tokens").toArray();
    QSet<QString> identifiers;
    for (qsizetype index = 0; index < array.size(); ++index) {
        if (!array.at(index).isObject()) {
            result.success = false;
            result.diagnostics << QString("Token %1 must be an object.").arg(index);
            continue;
        }
        const auto object = array.at(index).toObject();
        const auto id = object.value("id").toString();
        const auto category = object.value("category").toString();
        const auto type = object.value("type").toString();
        const auto description = object.value("description").toString();
        if (id.isEmpty() || category.isEmpty() || type.isEmpty() || description.isEmpty()) {
            result.success = false;
            result.diagnostics << QString("Token %1 is missing id, category, type, or description.").arg(index);
            continue;
        }
        if (identifiers.contains(id)) {
            result.success = false;
            result.diagnostics << QString("Duplicate token identifier '%1'.").arg(id);
            continue;
        }
        identifiers.insert(id);
        if (!categories.contains(category)) {
            result.success = false;
            result.diagnostics << QString("Token '%1' has unknown category '%2'.").arg(id, category);
        }
        if (!types.contains(type)) {
            result.success = false;
            result.diagnostics << QString("Token '%1' has unknown type '%2'.").arg(id, type);
        } else if (!typeMatches(category, type)) {
            result.success = false;
            result.diagnostics << QString("Token '%1' category '%2' is incompatible with type '%3'.")
                                      .arg(id, category, type);
        }
        std::function<void(const QString&, const QJsonValue&)> validateLiteral;
        validateLiteral = [&](const QString& path, const QJsonValue& value) {
            if (value.isUndefined()) {
                return;
            }
            if (value.isObject()) {
                const auto nested = value.toObject();
                for (auto iterator = nested.constBegin();
                     iterator != nested.constEnd();
                     ++iterator) {
                    validateLiteral(path + "." + iterator.key(), iterator.value());
                }
                return;
            }
            if (!literalMatches(type, value)) {
                result.success = false;
                result.diagnostics << QString(
                    "Token '%1' value at '%2' is invalid for type '%3'."
                ).arg(id, path, type);
            }
        };
        for (const auto& key : {
                 "value", "alias", "light", "dark", "highContrast",
                 "density", "platform"}) {
            validateLiteral(key, object.value(key));
        }
        const bool hasBase = object.contains("value") || object.contains("alias");
        const bool hasTheme = object.contains("light") && object.contains("dark");
        if (!hasBase && !hasTheme) {
            result.success = false;
            result.diagnostics << QString("Token '%1' needs value/alias or light and dark values.").arg(id);
        }
        const Token token{id, category, type, object};
        output->append(token);
        byId->insert(id, object);
    }

    enum class Visit { Visiting, Visited };
    QHash<QString, Visit> visits;
    std::function<void(const QString&, const QJsonValue&)> visitValue;
    std::function<void(const QString&)> visitToken;
    visitValue = [&](const QString& owner, const QJsonValue& value) {
        const auto referenced = aliasId(value);
        if (referenced.isEmpty()) {
            return;
        }
        if (!byId->contains(referenced)) {
            result.success = false;
            result.diagnostics << QString("Token '%1' references unknown alias '%2'.").arg(owner, referenced);
            return;
        }
        visitToken(referenced);
    };
    visitToken = [&](const QString& id) {
        if (visits.contains(id)) {
            if (visits.value(id) == Visit::Visited) {
                return;
            }
            if (visits.value(id) == Visit::Visiting) {
                result.success = false;
                result.diagnostics << QString("Circular alias detected at token '%1'.").arg(id);
                return;
            }
        }
        visits.insert(id, Visit::Visiting);
        const auto object = byId->value(id);
        for (const auto& key : {"alias", "value", "light", "dark"}) {
            visitValue(id, object.value(key));
        }
        for (const auto& key : {"highContrast", "density", "platform"}) {
            const auto overrides = object.value(key);
            if (overrides.isObject()) {
                for (const auto& value : overrides.toObject()) {
                    if (value.isObject()) {
                        for (const auto& nested : value.toObject()) {
                            visitValue(id, nested);
                        }
                    } else {
                        visitValue(id, value);
                    }
                }
            } else {
                visitValue(id, overrides);
            }
        }
        visits.insert(id, Visit::Visited);
    };
    for (const auto& token : std::as_const(*output)) {
        visitToken(token.id);
    }
    std::sort(output->begin(), output->end(), [](const Token& left, const Token& right) {
        return left.id < right.id;
    });
    return result;
}

[[nodiscard]] auto resolveValue(
    const QJsonValue& value,
    const QHash<QString, QJsonObject>& byId,
    const QString& scheme = {},
    const QString& contrast = {},
    const QString& density = {},
    const QString& platform = {}
) -> QJsonValue
{
    const auto referenced = aliasId(value);
    if (referenced.isEmpty()) {
        return value;
    }
    const auto target = byId.value(referenced);
    if (!platform.isEmpty() && target.value("platform").toObject().contains(platform)) {
        return resolveValue(target.value("platform").toObject().value(platform), byId, scheme, contrast, density, platform);
    }
    if (!density.isEmpty() && target.value("density").toObject().contains(density)) {
        return resolveValue(target.value("density").toObject().value(density), byId, scheme, contrast, density, platform);
    }
    if (contrast == "high") {
        auto high = target.value("highContrast");
        if (high.isObject() && !scheme.isEmpty()) {
            high = high.toObject().value(scheme);
        }
        if (!high.isUndefined()) {
            return resolveValue(high, byId, scheme, contrast, density, platform);
        }
    }
    if (!scheme.isEmpty() && target.contains(scheme)) {
        return resolveValue(target.value(scheme), byId, scheme, contrast, density, platform);
    }
    return resolveValue(target.contains("alias") ? target.value("alias") : target.value("value"),
                        byId, scheme, contrast, density, platform);
}

[[nodiscard]] auto selected(
    const QJsonObject& object,
    const QHash<QString, QJsonObject>& byId,
    const QString& scheme,
    const QString& contrast,
    const QString& density,
    const QString& platform
) -> QJsonValue
{
    QJsonValue value{QJsonValue::Undefined};
    if (!platform.isEmpty() && object.value("platform").toObject().contains(platform)) {
        value = object.value("platform").toObject().value(platform);
    } else if (!density.isEmpty() && object.value("density").toObject().contains(density)) {
        value = object.value("density").toObject().value(density);
    } else if (contrast == "high" && object.contains("highContrast")) {
        value = object.value("highContrast");
        if (value.isObject()) {
            value = value.toObject().value(scheme);
        }
    }
    if (value.isUndefined() && !scheme.isEmpty() && object.contains(scheme)) {
        value = object.value(scheme);
    }
    if (value.isUndefined()) {
        value = object.contains("alias") ? object.value("alias") : object.value("value");
    }
    return resolveValue(value, byId, scheme, contrast, density, platform);
}

[[nodiscard]] auto writeIfChanged(
    const QString& path,
    const QByteArray& data,
    QStringList* diagnostics
) -> bool
{
    QFile existing(path);
    if (existing.open(QIODevice::ReadOnly) && existing.readAll() == data) {
        return true;
    }
    QSaveFile output(path);
    if (!output.open(QIODevice::WriteOnly)) {
        diagnostics->append(QString("Cannot write '%1': %2").arg(path, output.errorString()));
        return false;
    }
    if (output.write(data) != data.size() || !output.commit()) {
        diagnostics->append(QString("Cannot commit '%1': %2").arg(path, output.errorString()));
        return false;
    }
    return true;
}

} // namespace

auto Generator::validate(const QByteArray& source) const -> Result
{
    QVector<Token> tokens;
    QHash<QString, QJsonObject> byId;
    return parse(source, &tokens, &byId);
}

auto Generator::generate(
    const QString& schemaPath,
    const QString& sourcePath,
    const QString& outputDirectory
) const -> Result
{
    if (!QFileInfo::exists(schemaPath)) {
        return {false, {QString("Schema file does not exist: %1").arg(schemaPath)}};
    }
    QFile source(sourcePath);
    if (!source.open(QIODevice::ReadOnly)) {
        return {false, {QString("Cannot read '%1': %2").arg(sourcePath, source.errorString())}};
    }
    QVector<Token> tokens;
    QHash<QString, QJsonObject> byId;
    auto result = parse(source.readAll(), &tokens, &byId);
    if (!result) {
        return result;
    }
    QDir directory;
    if (!directory.mkpath(outputDirectory)) {
        return {false, {QString("Cannot create output directory '%1'.").arg(outputDirectory)}};
    }
    result.success =
        writeIfChanged(outputDirectory + "/Tokens.qml", qml(tokens), &result.diagnostics)
        && writeIfChanged(outputDirectory + "/tokens.cppm", cpp(tokens), &result.diagnostics)
        && writeIfChanged(outputDirectory + "/tokens-reference.md", markdown(tokens), &result.diagnostics);
    return result;
}

auto Generator::qml(const QVector<Token>& tokens) -> QByteArray
{
    QHash<QString, QJsonObject> byId;
    for (const auto& token : tokens) {
        byId.insert(token.id, token.source);
    }
    QByteArray output = generatedBanner;
    output += "pragma Singleton\nimport QtQuick\n\nQtObject {\n";
    output += "    function platformName() { return Qt.platform.os === \"osx\" ? \"macos\" : Qt.platform.os }\n";
    for (const auto& token : tokens) {
        const QByteArray qmlType = token.type == "color" ? "color"
            : token.type == "fontFamily" || token.type == "easing"
                || token.type == "string" ? "string"
            : "real";
        output += "    readonly property " + qmlType + " " + token.id.toUtf8()
            + ": resolve(\"" + token.id.toUtf8() + "\", Theme.effectiveDark)\n";
    }
    output += "\n    function resolve(id, effectiveDark) {\n        const scheme = effectiveDark ? \"dark\" : \"light\"\n"
              "        const platform = platformName()\n"
              "        const record = records[id]\n        if (!record) return undefined\n"
              "        if (record.platform && record.platform[platform] !== undefined) return record.platform[platform]\n"
              "        if (record[scheme] !== undefined) return record[scheme]\n"
              "        return record.value\n    }\n\n"
              "    readonly property var records: ({\n";
    for (qsizetype i = 0; i < tokens.size(); ++i) {
        const auto& token = tokens.at(i);
        const auto& object = token.source;
        output += "        \"" + token.id.toUtf8() + "\": {";
        const auto base = selected(object, byId, {}, {}, {}, {});
        output += "\"value\":" + qmlLiteral(base).toUtf8();
        for (const auto& scheme : {"light", "dark"}) {
            if (token.type == "color" || object.contains(scheme)) {
                output += ",\"" + QByteArray(scheme) + "\":"
                    + qmlLiteral(selected(object, byId, scheme, "normal", {}, {})).toUtf8();
            }
        }
        if (object.value("platform").isObject()) {
            output += ",\"platform\":{";
            auto keys = object.value("platform").toObject().keys();
            std::sort(keys.begin(), keys.end());
            for (qsizetype keyIndex = 0; keyIndex < keys.size(); ++keyIndex) {
                if (keyIndex) output += ",";
                output += "\"" + keys.at(keyIndex).toUtf8() + "\":"
                    + qmlLiteral(selected(object, byId, {}, {}, {}, keys.at(keyIndex))).toUtf8();
            }
            output += "}";
        }
        output += "}";
        output += i + 1 == tokens.size() ? "\n" : ",\n";
    }
    output += "    })\n}\n";
    return output;
}

auto Generator::cpp(const QVector<Token>& tokens) -> QByteArray
{
    QByteArray output = generatedBanner;
    output += "export module pds.native.tokens;\n\nimport std;\n\n"
              "export namespace pds::native::tokens {\n"
              "enum class TokenId {\n";
    for (const auto& token : tokens) {
        output += "    " + cppName(token.id).toUtf8() + ",\n";
    }
    output += "};\n\nstruct TokenInfo final { TokenId id; std::string_view name; std::string_view category; std::string_view type; };\n"
              "inline constexpr std::array<TokenInfo, " + QByteArray::number(tokens.size()) + "> All{{\n";
    for (const auto& token : tokens) {
        output += "    {TokenId::" + cppName(token.id).toUtf8() + ", \"" + token.id.toUtf8()
            + "\", \"" + token.category.toUtf8() + "\", \"" + token.type.toUtf8() + "\"},\n";
    }
    output += "}};\n}\n";
    return output;
}

auto Generator::markdown(const QVector<Token>& tokens) -> QByteArray
{
    QByteArray output = "<!-- Generated by PdsTokenGenerator. Do not edit. -->\n"
                        "# Token reference\n\n"
                        "| Identifier | Category | Type | Classification | Upstream source | Upstream value |\n"
                        "|---|---|---|---|---|---|\n";
    for (const auto& token : tokens) {
        output += "| `" + token.id.toUtf8() + "` | " + token.category.toUtf8() + " | "
            + token.type.toUtf8() + " | "
            + token.source.value("classification").toString().toUtf8() + " | `"
            + token.source.value("upstreamSource").toString().toUtf8() + "` | `"
            + token.source.value("upstreamValue").toVariant().toString().toUtf8() + "` |\n";
    }
    return output;
}

}
